version: "3.7"
services:
  nest:
    container_name: nest
    image: "famo1245/planj:v2"
    networks:
      - backend
      -
  nginx:
    container_name: nginx
    image: "famo1245/nginx:v1"
    ports:
      - "80:80"
    networks:
      - backend

networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge
